# Generated by Django 6.0.6 on 2026-06-04 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('americano', 'Americano'), ('round-robin', 'Round Robin'), ('single-elimination', 'Single Elimination')], max_length=32)),
                ('sport', models.CharField(choices=[('padel', 'Padel')], max_length=32)),
                ('courts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rounds', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
