# Generated by Django 6.0.6 on 2026-06-04 18:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tournament_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('match_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_at', models.DateTimeField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament')),
            ],
            options={
                'ordering': ['tournament', 'match_number'],
            },
        ),
    ]
