# Generated by Django 6.0.6 on 2026-06-04 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_team_options_team_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0, help_text='Leave as 0 for no maximum number of rounds (uncapped). Set to a positive value to cap the tournament at that many rounds.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
