# Generated by Django 6.0.6 on 2026-06-04 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_match_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', help_text='Public clubs can be joined by users (coming soon). Private clubs are invite-only.', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0, help_text='Leave as 0 for no maximum number of rounds.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
