# Generated by Django 6.0.6 on 2026-06-04 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_club_visibility_alter_tournament_rounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, help_text='Optional. Town or city, e.g. "Cape Town" or "Durbanville".', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), ('phone', ''), _negated=True), name='club_requires_email_or_phone'),
        ),
    ]
