# Generated by Django 6.0.6 on 2026-06-05 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_club_email_club_location_club_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='Selected when creating the tournament. Used to generate matches.', related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
