# Generated by Django 6.0.6 on 2026-06-09 17:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_match_and_team_clubs(apps, schema_editor):
    Match = apps.get_model("core", "Match")
    Team = apps.get_model("core", "Team")

    for match in Match.objects.select_related("tournament").iterator():
        club_id = match.tournament.club_id
        if match.club_id != club_id:
            match.club_id = club_id
            match.save(update_fields=["club_id"])

    for team in Team.objects.select_related("match__tournament").iterator():
        club_id = team.match.tournament.club_id
        if team.club_id != club_id:
            team.club_id = club_id
            team.save(update_fields=["club_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tournament_starts_at_game_duration_break_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.club'),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='core.club'),
        ),
        migrations.RunPython(backfill_match_and_team_clubs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tournament',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Break between rounds (hours and minutes). Use 00:00 for no break.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400), help_text='Length of each round of play (hours and minutes).'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='Selected after the tournament is created. Used to generate matches.', related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0, help_text='Leave as 0 for no maximum when first generating matches. After matches are created, this is updated to the actual number of rounds.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
