# Generated by Django 6.0.6 on 2026-06-22 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tournament_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_teams', to='core.club')),
                ('members', models.ManyToManyField(blank=True, related_name='club_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['club', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Round-robin only. Select existing club teams after creating the tournament.', related_name='tournaments', to='core.clubteam'),
        ),
        migrations.DeleteModel(
            name='TournamentTeam',
        ),
    ]
