# Generated by Django 6.0.6 on 2026-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_unify_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('padel', 'Padel'), ('dodgeball', 'Dodgeball')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='When the tournament begins. Matches are scheduled from this time.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Select existing club teams after creating the tournament (round robin, or dodgeball single elimination).', related_name='tournaments', to='core.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(blank=True, choices=[('americano', 'Americano'), ('round-robin', 'Round Robin'), ('single-elimination', 'Single Elimination')], default='', max_length=32),
        ),
    ]
